services:
  code:
    image: ghcr.io/hung319/vscode-server:latest
    container_name: code
    restart: unless-stopped
    ports:
      - 8585:8585
    volumes:
      - ./workspace:/workspace
    environment:
      - TOKEN=<token>
networks: {}
