name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Đăng nhập vào GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .

      # Push Docker Image lên GitHub Packages
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
